services:
  - name: frontend
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-backend-render-url
  - name: backend
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-connection-string
